def keywords():
    keywords = [
    "auto",
    "bool",
    "stop",
    "situation",
    "catch",
    "char",
    "class",
    "fix",
    "continue",
    "drop",
    "act",
    "double",
    "other",
    "enum",
    "false",
    "float",
    "as",
    "jump",
    "lets",
    "#include",
    "int",
    "long",
    "namespace",
    "endl",
    "private",
    "protected",
    "public",
    "back",
    "short",
    "signed",
    "sizeof",
    "static",
    "struct",
    "switch",
    "true",
    "try",
    "unsigned",
    "empty",
    "during",
    "output",
    "input",
    "exception",
    "throw",
    "throws",
    "Exception",
    "Method",
    "endl.",
    ]
    return keywords

def operators():
    operators = {
    "+": "PLUS",
    "-": "MINUS",
    "*": "MUL",
    "/": "DIV",
    "%": "MOD",
    "+=": "PLUSEQ",
    "-=": "MINUSEQ",
    "*=": "MULEQ",
    "/=": "DIVEQ",
    "++": "INC",
    "--": "DEC",
  #  "|": "OR",
  #  "&&": "AND",
    }
    return operators

def delimiters():
    delimiters = {
    "\t": "TAB",
    "\n": "NEWLINE",
    "(": "LPAR",
    ")": "RPAR",
    "[": "LBRACE",
    "]": "RBRACE",
    "{": "LCBRACE",
    "}": "RCBRACE",
    "=": "EQUAL",
    ":": "COLON",
    ",": "COMMA",
    ";": "SEMICOL",
    "<<": "OUT",
    ">>": "IN",
     ".": "dot",
     "<": "LESS THAN",
     ">": "GREATER THAN",
    #".\t": "TERMINATOR",
    #".\n": "TERMINATOR",
    }
    return delimiters



def opDelim():
    opDelim = {
    "+": "PLUS",
    "-": "MINUS",
    "*": "MUL",
    "/": "DIV",
    "%": "MOD",
    "+=": "PLUSEQ",
    "-=": "MINUSEQ",
    "*=": "MULEQ",
    "/=": "DIVEQ",
    "++": "INC",
    "--": "DEC",
    "||": "OR",
    "&&": "AND",
     "\t": "TAB",
    "\n": "NEWLINE",
    "(": "LPAR",
    ")": "RPAR",
    "[": "LBRACE",
    "]": "RBRACE",
    "{": "LCBRACE",
    "}": "RCBRACE",
    "=": "EQUAL",
    ":": "COLON",
    ",": "COMMA",
    ";": "SEMICOL",
    "<<": "OUT",
    ">>": "IN",
     "<": "LESS THAN",
     ">": "GREATER THAN",
     "<=": "Less Than and Equal",
     ">=": "Greater than and equal",
     "==": "Equal To",
       "|": "Invalid tokenn",
    "&": "Invalid Tokenn",
    
    }
    return opDelim